version: "3.5"


services:

    git-db:
      image: postgres:alpine
      container_name: git-db
      hostname: git-db
      restart: always
      environment:
        - POSTGRES_DB=${GOGS_POSTGRESQL_DATABASE}
        - POSTGRES_USER=${GOGS_POSTGRESQL_USER}
        - POSTGRES_PASSWORD=${GOGS_POSTGRESQL_PASSWORD}
      ports:
        - ${GOGS_POSTGRESQL_PORT}:5432
      networks:
        - git-network
      volumes:
        - gogs-postgresql-data:/var/lib/postgresql/data
          
    git:
      image: gogs/gogs:latest
      container_name: git
      hostname: git
      restart: always
      environment:
        - RUN_CROND=true
      volumes:
        - gogs-data:/data
      networks:
        - git-network
      ports:
        - ${GOGS_SSH_PORT}:22
        - ${GOGS_HTTP_PORT}:3000
      depends_on:
        - git-db


networks:

    git-network:
      name: git-network
      driver: bridge


volumes:

    gogs-data:
      driver_opts:
        type: none
        device: ${GOGS_DATA}
        o: bind

    gogs-mysql-data:
      driver_opts:
        type: none
        device: ${GOGS_POSTGRESQL_DATA}
        o: bind
