version: "3.5"


services:

    git-db:
      image: mysql:latest
      container_name: git-db
      hostname: git-db
      restart: always
      environment:
          - MYSQL_DATABASE=${GOGS_MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${GOGS_MYSQL_ROOT_PASSWORD}
          - MYSQL_PASSWORD=${GOGS_MYSQL_USER_PASSWORD}
          - MYSQL_USER=gogs
      ports:
        - ${GOGS_MYSQL_PORT}:3306
      networks:
        - git-network
      volumes:
          - gogs-mysql-data:/var/lib/mysql
          
    git:
      image: gogs/gogs:latest
      container_name: git
      hostname: git
      restart: always
      environment:
        - RUN_CROND=true
      volumes:
        - gogs-data:/data
      networks:
        - git-network
      ports:
        - ${GOGS_SSH_PORT}:22
        - ${GOGS_HTTP_PORT}:80
      depends_on:
        - git-db


networks:
    git-network:
      name: git-network
      driver: bridge


volumes:

    gogs-data:
      driver_opts:
        type: none
        device: ${GOGS_DATA}
        o: bind

    gogs-mysql-data:
      driver_opts:
        type: none
        device: ${GOGS_MYSQL_DATA}
        o: bind        
