version: "3.3"


services:

    git:
      image: gogs/gogs:latest
      container_name: git
      hostname: git.local
      restart: always
      environment:
        - RUN_CROND=true
      volumes:
        - gogs-data:/data
      networks:
        - git-network
      ports:
        - ${GOGS_SSH_PORT}:22
        - ${GOGS_HTTP_PORT}:80

    git-db:
      image: mysql:latest
      container_name: git-db
      hostname: git-db.local
      restart: always
      environment:
          - MYSQL_DATABASE=${GOGS_MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${GOGS_MYSQL_ROOT_PASSWORD}
      ports:
        - ${GOGS_MYSQL_PORT}:3306
      networks:
        - git-network
      volumes:
          - gogs-mysql-data:/var/lib/mysql


networks:
    git-network:
      driver: bridge


volumes:

    gogs-data:
      driver_opts:
        type: none
        device: ${GOGS_ROOT}/data
        o: bind

    gogs-mysql-data:
      driver_opts:
        type: none
        device: ${GOGS_ROOT}/mysql/data
        o: bind        